name: PowrCore
version: 1.1
main: PowrCore\FaizDev\PowrCore
authors: ["FaizDev", "ItsToxicGG"]
api: 4.0.0

permissions:
  settings.cmd:
    default: op
  fly.cmd:
    default: op   
  namecolor.cmd:
    default: op
